tasks:
  - name: Open the readme, contract and test
    command: gp open README.md && gp open agent-output.txt
  
  - name: Install dependencies
    command: pip install jupyterlab==4.2.1 pyautogen==0.2.27 crewai==0.30.11 crewai-tools==0.2.6 duckduckgo-search==6.1.4 agentops==0.2.0