tasks:
  - init: pip install -r requirements.txt
  
  - name: Open the readme, contract and test
    command: gp open README.md && gp open CrewAI.ipynb

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers