tasks:
  - name: Setup
    init: curl -LsSf https://astral.sh/uv/install.sh | sh
    #command: gp open CrewAI.ipynb

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers