tasks:
  - name: Setup
    init: pip install -r requirements.txt
    command: gp open CrewAI.ipynb

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers